
# in case of update
## $ conda env update --prefix ./env --file environment.yml  --prune

name: bali_covid_dash_app #Environment name
dependencies:
  - python=3.7.6
  - numpy
  - pandas
  - pip

  - pip:
    - dash
    - dash-renderer
    - dash-core-components
    - dash-html-components
    - dash_bootstrap_components
    - plotly
    - gunicorn # for app deployment